### ISSUE TITLE
ImportError: cannot import name 'exists' from 'aemeasure'

### ISSUE THREAD

**Issue by qiangsun89** [d-krupke/ALENEX24-partial-coverage-path-planning#1]
already install aemeasure-0.2.9，
when run >>>python3 07_solve_full_coverage_grids.py 
error : Traceback (most recent call last):
  File "07_solve_full_coverage_grids.py", line 8, in <module>
    from aemeasure import Measurement, exists
ImportError: cannot import name 'exists' from 'aemeasure' (/home/qiang/.local/lib/python3.8/site-packages/aemeasure/__init__.py)

**Comment by d-krupke** [comment]
Thanks for reporting this problem. This code is already quite old and used an older version of AeMeasure (which has since been replaced by AlgBench in my daily use). A workaround is to just replace the `exists`-part by False, as it just checks if the computation already has been performed in case it has been aborted before completion the last time. I will check if I can do a simple fix.

**Comment by d-krupke** [comment]
I just simply added the old aemeasure version to the repository. The code should now automatically load the old local version of it.
