### ISSUE TITLE
GurobiError: Model too large for size-limited license

### ISSUE THREAD

**Issue by qiangsun89** [d-krupke/ALENEX24-partial-coverage-path-planning#2]
Hello, 
when I'm using pcpptc for path planning, I always get the following error during the optimization step: 
“GurobiError: Model too large for size-limited license; visit https://www.gurobi.com/free-trial for a full license.”
Is it possible to use COIN-OR instead of Gurobi?

**Comment by d-krupke** [comment]
Gurobi could be replaced by any MIP-solver that supports lazy constraints via callbacks  (which should  include COIN-OR). However, this would require to migrate the Linear Relaxation and the LNS-part as my code uses Gurobi directly. This should be relatively easy, but the code in this repository is an academic prototype accompanying a paper, for which the analysis has been done with Gurobi. Since Gurobi provides free academic licenses and is in my opinion the best MIP-solver, I am not planning to implement a COIN-OR version.
